name: instagram_clone_application
description: "The Application Layer For The Instagram Clone"
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

publish_to: none

dependencies:
  bloc: ^8.1.4
  dartz: ^0.10.1
  dev: ^1.0.0
  equatable: ^2.0.5
  firebase_auth: ^5.1.1
  flutter:
    sdk: flutter

  #project dependencies
  formz: ^0.7.0
  instagram_clone_domain:
    path: ../instagram_clone_domain
  intl: ^0.19.0
  meta: ^1.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  bloc_test: ^9.1.7
  mocktail: ^1.0.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec