name: instagram_clone_infrastructure
description: "The Infrastructure Layer For Instagram Clone."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

publish_to: none

dependencies:
  dartz: ^0.10.1
  cloud_firestore: ^5.1.0
  firebase_auth: ^5.1.1
  flutter:
    sdk: flutter

  google_sign_in: ^6.2.1
  instagram_clone_application:
    path: ../instagram_clone_application

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mocktail: ^1.0.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec