name: instagram_clone_infrastructure
description: "The Infrastructure Layer For Instagram Clone."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

publish_to: none

dependencies:
  dartz: ^0.10.1
  cloud_firestore: ^5.1.0
  firebase_auth: ^5.1.1
  flutter:
    sdk: flutter

  google_sign_in: ^6.2.1
  instagram_clone_application:
    path: ../instagram_clone_application
  instagram_clone_shared:
    path: ../instagram_clone_shared
  firebase_core: ^3.2.0
  internet_connection_checker: ^1.0.0+1
  injectable: ^2.4.4
  get_it: ^8.0.2
  mailer: ^6.1.2
  uuid: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
  build_runner: ^2.4.11
  injectable_generator: ^2.6.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec